name: Delete namespace on branch deletion
on: delete
concurrency:
  group: rn2021-${{ github.event.ref }}
  cancel-in-progress: true

jobs:
  delete:
    if: github.event.ref_type == 'branch'
    env:
      REF: ${{ github.event.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Variable setup
        uses: ./.github/actions/variables-setup

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Delete namespace
        run: kubectl delete namespace $BRANCH
